stages:
  - static analysis
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

image: python:3.7

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

static:
  stage: static analysis
  script:
    - pip install black==20.8b1 flake8==3.8.4
    - black src/piven/*.py
    - flake8 --max-line-length=120 src/piven/*.py

unit_tests:
  stage: test
  script:
    - pwd
    - ls -l
    - export PYTHONPATH="$PYTHONPATH:."
    - python -c "import sys;print(sys.path)"
    - pip install pytest>=2.0.0
    - pip install .
    - pytest
